/* eslint-disable no-unused-vars */
export enum Skill {
    HTML = 'HTML',
    CSS = 'CSS',
    JavaScript = 'JavaScript',
    TypeScript = 'TypeScript',
    React = 'React',
    Next = 'Next.js',
    Vue = 'Vue',
    Angular = 'Angular',
    Node = 'Node.js',
    Nest = 'NestJS',
    Go = 'Golang',
    Redux = 'Redux',
    ReduxThunk = 'Redux thunk',
    ReduxToolkit = 'Redux toolkit',
    Zustand = 'Zustand',
    MobX = 'MobX',
    Jest = 'Jest',
    Cypress = 'Cypress',
    WebSocket = 'WebSocket',
    MySql = 'MySql',
    SQLite = 'SQLite',
    PostgreSQL = 'PostgreSQL',
    MongoDB = 'MongoDB',
    Oracle = 'Oracle',
    Redis = 'Redis',
    Apache = 'Apache',
    Prisma = 'Prisma',
    GORM = 'GORM',
    Sequelize = 'Sequelize',
    TypeORM = 'TypeORM',
    Mongoose = 'Mongoose',
}
